# teloxplorer/meta.yaml

{% set name = "teloxplorer" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .
  #git_url: https://github.com/hhuili/Teloxplorer.git
  #git_rev: v{{ version }}

build:
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - {{ compiler('cxx') }}
    - make

  run:
    - python >=3.8
    - numpy
    - pysam
    - regex
    - minimap2

test:
  imports:
    - teloxplorer
  commands:
    - teloxplorer --help
    - telox-align --help
    - telox-length --help
    - telox-variants --help
    - telox-asm --help
    - command -v BLOOM
    - command -v minimap2

about:
  home: "https://github.com/hhuili/Teloxplorer"
  license: "MIT"
  summary: "A pipeline for telomere length and variation analysis."
