# Copyright (C) 2025 Huihui Li <hhui.li@outlook.com>. Licensed under GNU GPL v3.0.

from pathlib import Path
import itertools
import numpy as np
from natsort import natsort_key
from polyleven import levenshtein
from collections import defaultdict, Counter
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from typing import Optional, Union
from functools import lru_cache
import pyabpoa
from telox import telohmm
import hdbscan

from . import telox_utils
from . import logger as log_utils

@dataclass
class TVRConfig:
    motif: str = "TTAGGG"
    kmers: str = "5,6,7,8,9"
    min_tvr_copy: int = 2
    chunk_size: int = 2000
    max_depth: int = 150
    min_cluster_size: int = 5
    cluster_epsilon: float = 0.25
    debug: bool = False
    is_asm: bool = False
    include_canonical: bool = False

    @classmethod
    def from_params(cls, preset_name=None, **kwargs):
        return telox_utils.apply_preset_and_overrides(cls, preset_name, PRESETS, **kwargs)

PRESETS = {
    'human': telox_utils.make_config_from_preset(TVRConfig, 'human',
        kmers="5,6,7,8,9",
        include_canonical=False,
        cluster_epsilon=0.25,
        min_cluster_size=5
    ),
    'human-r9': telox_utils.make_config_from_preset(TVRConfig, 'human-r9',
        kmers="5,6,7,8",
        include_canonical=False,
        cluster_epsilon=0.25,
        min_cluster_size=5
    ),
    'mouse': telox_utils.make_config_from_preset(TVRConfig, 'mouse',
        kmers="5,6,7,8,9",
        include_canonical=False,
        cluster_epsilon=0.25,
        min_cluster_size=5
    ),
    'yeast': telox_utils.make_config_from_preset(TVRConfig, 'yeast',
        kmers="2,3,4",
        include_canonical=True,
        cluster_epsilon=0.15,
        min_cluster_size=10
    ),
    'arabidopsis': telox_utils.make_config_from_preset(TVRConfig, 'arabidopsis',
        kmers="5,6,7,8,9",
        include_canonical=False,
        cluster_epsilon=0.25,
        min_cluster_size=5
    ),
    'arabidopsis-r9': telox_utils.make_config_from_preset(TVRConfig, 'arabidopsis-r9',
        kmers="5,6,7,8,9",
        include_canonical=False,
        cluster_epsilon=0.25,
        min_cluster_size=5
    )
}

@dataclass
class TelSeqHeader:
    read_id: str
    chrom: str
    chrom_phase: str
    arm: str
    tel_length: str
    tel_start: str
    tel_end: str
    strand: str

    @classmethod
    def parse(cls, header_string: str) -> "TelSeqHeader":
        parts = header_string.split('|')

        if len(parts) < 8:
            raise ValueError(
                f"\n[Error] Invalid FASTA header format: '>{header_string}'\n"
                f"telox_tvr requires the current schema generated by telox_length:\n"
                f"  >read_id|chrom|chrom_phase|arm|tel_length|tel_start|tel_end|strand"
            )

        *read_id_parts, chrom, chrom_phase, arm, tel_length, tel_start, tel_end, strand = parts

        return cls(
            read_id="|".join(read_id_parts),
            chrom=chrom,
            chrom_phase=chrom_phase,
            arm=arm,
            tel_length=tel_length,
            tel_start=tel_start,
            tel_end=tel_end,
            strand=strand
        )

def read_fasta_generator(file_path):
    with open(file_path, 'r') as f:
        header_raw = None
        sequence = []
        for line in f:
            line = line.strip()
            if line.startswith('>'):
                if header_raw:
                    header = TelSeqHeader.parse(header_raw)
                    seq_str = "".join(sequence)
                    if header.arm in ['L', 'p']:
                        seq_str = telox_utils.sequence_revcomp(seq_str)
                    yield header, seq_str
                header_raw = line[1:]
                sequence = []
            else:
                sequence.append(line.upper())

        if header_raw:
            header = TelSeqHeader.parse(header_raw)
            seq_str = "".join(sequence)
            if header.arm in ['L', 'p']:
                seq_str = telox_utils.sequence_revcomp(seq_str)
            yield header, seq_str

@lru_cache(maxsize=1024)
def get_cyclic_shifts(s):
    return tuple([s[i:] + s[:i] for i in range(len(s))])

@lru_cache(maxsize=4096)
def get_canonical_form(s):
    return min(get_cyclic_shifts(s))

@lru_cache(maxsize=8192)
def find_best_representative_repeat(shifts_tuple, reference_repeat):
    rc_ref = telox_utils.sequence_revcomp(reference_repeat)

    def count_blocks(seq):
        return 1 + sum(1 for i in range(1, len(seq)) if seq[i] != seq[i-1])

    def get_best_shift(target_ref, alt_start_char):
        def score_shift(shift):
            return (
                levenshtein(shift, target_ref),
                count_blocks(shift),
                not shift.startswith(target_ref),
                not shift.startswith(target_ref[0]),
                not shift.startswith(alt_start_char)
            )

        return min(shifts_tuple, key=score_shift)

    best_fwd = get_best_shift(reference_repeat, rc_ref[0])
    best_rev = get_best_shift(rc_ref, reference_repeat[0])

    dist_fwd = levenshtein(best_fwd, reference_repeat)
    dist_rev = levenshtein(best_rev, rc_ref)

    return best_fwd if dist_fwd <= dist_rev else best_rev

@lru_cache(maxsize=8192)
def get_standardized_kmer(kmer, ref_motif):
    if not kmer or "N" in kmer:
        return kmer
    shifts_tuple = get_cyclic_shifts(kmer)
    return find_best_representative_repeat(shifts_tuple, ref_motif)

def find_unit(seq, k_values, reference_repeat, min_tvr_copy):
    results = defaultdict(lambda: defaultdict(int))
    seq = seq.upper()
    seq_len = len(seq)

    for k in k_values:
        for phase in range(k):
            last_kmer = None
            current_run_length = 0
            last_kmer_valid = False

            for start in range(phase, seq_len - k + 1, k):
                kmer = seq[start:start+k]

                if kmer == last_kmer:
                    if last_kmer_valid:
                        current_run_length += 1
                else:
                    if last_kmer and last_kmer_valid and current_run_length > results[k][last_kmer]:
                        results[k][last_kmer] = current_run_length

                    is_valid = ('N' not in kmer)

                    if not is_valid:
                        last_kmer_valid = False
                        current_run_length = 0
                    else:
                        last_kmer_valid = True
                        current_run_length = 1
                    last_kmer = kmer

            if last_kmer and last_kmer_valid and current_run_length > results[k][last_kmer]:
                results[k][last_kmer] = current_run_length

    filtered_results = defaultdict(dict)

    for k, raw_counts in results.items():
        std_max_runs = defaultdict(int)

        for raw_kmer, run_len in raw_counts.items():
            if len(set(raw_kmer)) == 1:
                continue
            std_kmer = get_standardized_kmer(raw_kmer, reference_repeat)
            if run_len > std_max_runs[std_kmer]:
                std_max_runs[std_kmer] = run_len

        for std_kmer, max_run in std_max_runs.items():
            if max_run >= min_tvr_copy:
                filtered_results[k][std_kmer] = max_run

    return filtered_results

def decompose_telomere_sequence(motif_units, sequence, k_values, canonical_motif, canonical_set):
    all_counts = defaultdict(int)
    variants_loc = []

    seq_len = len(sequence)
    ref_len = len(canonical_motif)
    ref_canonical = get_canonical_form(canonical_motif)

    known_tvrs = set()
    known_tvrs_runs = {}
    for k, units in motif_units.items():
        for u, count in units.items():
            if get_canonical_form(u) != ref_canonical and u not in canonical_set:
                std_u = get_standardized_kmer(u, canonical_motif)
                known_tvrs.add(std_u)
                known_tvrs_runs[std_u] = max(known_tvrs_runs.get(std_u, 0), count)

    canonical_lens = set(len(m) for m in canonical_set)
    valid_k = sorted(list(set(k_values + list(canonical_lens) + [ref_len])))

    canonical_shifts = set()
    for c_m in canonical_set:
        canonical_shifts.update(get_cyclic_shifts(c_m))
    canonical_shifts.update(get_cyclic_shifts(canonical_motif))

    anchors = []
    i = 0
    sorted_canonical = sorted(list(canonical_set), key=len, reverse=True)

    while i < seq_len:
        run = []
        curr_i = i
        matched = True
        while matched and curr_i < seq_len:
            matched = False
            for m in sorted_canonical:
                m_len = len(m)
                if curr_i + m_len <= seq_len and sequence[curr_i : curr_i + m_len] == m:
                    run.append((curr_i, curr_i + m_len, m))
                    curr_i += m_len
                    matched = True
                    break

        if len(run) >= 3:
            for c in range(1, len(run) - 1):
                anchors.append(run[c])
            i = curr_i
        elif len(run) > 0:
            i = curr_i
        else:
            i += 1

    std_cache = {}
    dist_cache = {}
    def fast_std(seq_str):
        if seq_str not in std_cache:
            std_cache[seq_str] = get_standardized_kmer(seq_str, canonical_motif)
        return std_cache[seq_str]

    def fast_dist(seq_str):
        if seq_str not in dist_cache:
            dist_cache[seq_str] = min(levenshtein(seq_str, s) for s in canonical_shifts)
        return dist_cache[seq_str]

    def process_local_dp(gap_start, gap_end, anchor_kmer):
        length = gap_end - gap_start
        gap_seq = sequence[gap_start:gap_end]

        dp = [float('inf')] * (length + 1)
        dp[0] = 0
        backtrack = [-1] * (length + 1)

        for j in range(1, length + 1):
            for k in valid_k:
                if j - k >= 0 and dp[j - k] != float('inf'):
                    sub_seq = gap_seq[j-k : j]
                    std_sub = fast_std(sub_seq)

                    in_phase = (sub_seq == std_sub)
                    phase_penalty = 0.0 if in_phase else 2.0 

                    if sub_seq in canonical_set or (k == ref_len and sub_seq == canonical_motif):
                        cost = 0.0
                    elif std_sub in known_tvrs:
                        run_count = known_tvrs_runs.get(std_sub, 1)
                        bonus = min(0.08, run_count * 0.002)
                        cost = 0.1 - bonus + phase_penalty
                    elif sub_seq in canonical_shifts:
                        cost = 0.5 + phase_penalty
                    else:
                        d = fast_dist(sub_seq)
                        if d <= 3:
                            cost = d + phase_penalty
                        else:
                            cost = 10.0 + d + phase_penalty

                    cost += 0.05
                    if dp[j-k] + cost < dp[j]:
                        dp[j] = dp[j-k] + cost
                        backtrack[j] = j - k

        res_locs = []
        curr = length
        cuts = []
        while curr > 0:
            prev = backtrack[curr]
            if prev == -1:
                break
            cuts.append((gap_start + prev, gap_start + curr))
            curr = prev
        cuts.reverse()

        for c_start, c_end in cuts:
            sub_seq = sequence[c_start:c_end]
            std_sub = fast_std(sub_seq)

            if sub_seq in canonical_set or std_sub in known_tvrs or fast_dist(sub_seq) <= 3:
                res_locs.append((c_start, c_end, std_sub))
            else:
                res_locs.append((c_start, c_end, "N" * ref_len))

        return res_locs

    curr_pos = 0
    a_idx = 0
    while curr_pos < seq_len:
        if a_idx < len(anchors):
            a_start, a_end, a_kmer = anchors[a_idx]
            if curr_pos < a_start:
                locs = process_local_dp(curr_pos, a_end, a_kmer)
                for loc in locs:
                    variants_loc.append(loc)
                    all_counts[loc[2]] += 1
                curr_pos = a_end
                a_idx += 1
            else:
                variants_loc.append((a_start, a_end, a_kmer))
                all_counts[a_kmer] += 1
                curr_pos = a_end
                a_idx += 1
        else:
            if curr_pos < seq_len:
                locs = process_local_dp(curr_pos, seq_len, None)
                for loc in locs:
                    variants_loc.append(loc)
                    all_counts[loc[2]] += 1
                curr_pos = seq_len

    variants_loc.sort(key=lambda x: x[0])

    return all_counts, variants_loc

def process_chunk_data(records_chunk, k_values, canonical_set, std_motif, min_tvr_copy, include_canonical):
    chunk_summary = {}
    chunk_plot_data = {}
    chunk_read_meta = {}
    chunk_tvr_map = defaultdict(list)
    chunk_all_map = defaultdict(list)
    backbone_form = get_canonical_form(std_motif)

    for header, sequence in records_chunk:
        canonical_motif = std_motif
        chunk_read_meta[header.read_id] = (header.chrom, header.chrom_phase, header.arm)

        motif_units = find_unit(sequence, k_values, canonical_motif, min_tvr_copy)
        all_counts, offsets = decompose_telomere_sequence(motif_units, sequence, k_values, canonical_motif, canonical_set)

        for unit, count in all_counts.items():
            if "N" in unit:
                continue
            chrom_key = (header.chrom, header.chrom_phase)
            if chrom_key not in chunk_summary:
                chunk_summary[chrom_key] = {}
            if header.arm not in chunk_summary[chrom_key]:
                chunk_summary[chrom_key][header.arm] = defaultdict(int)
            chunk_summary[chrom_key][header.arm][unit] += count

        tvr_entries = []
        for v_start, v_end, kmer in offsets:
            chunk_all_map[header.read_id].append(kmer)

            if "N" in kmer:
                continue

            is_backbone = (get_canonical_form(kmer) == backbone_form)

            if not is_backbone or include_canonical:
                chunk_tvr_map[header.read_id].append((v_start, kmer, v_start, v_end))
                tvr_entries.append(f"{v_start},{v_end},{kmer}")

        tvr_str = ";".join(tvr_entries) if tvr_entries else "."
        chunk_plot_data[header.read_id] = (header.tel_length, tvr_str, header.chrom, header.chrom_phase)

    return chunk_summary, chunk_plot_data, chunk_tvr_map, chunk_all_map, chunk_read_meta

def _cluster_reads(reads_list, token_strings_dict, config):
    n = len(reads_list)

    if n == 0:
        return [], set()
    if n == 1:
        return [reads_list], set()

    token_lengths = [len(token_strings_dict[r]) for r in reads_list]
    median_len = int(np.median(token_lengths))

    if median_len == 0:
        return [reads_list], set()

    tvr_tokens = [token_strings_dict[r] for r in reads_list]

    dist_matrix = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(i + 1, n):
            seq_i = tvr_tokens[i]
            seq_j = tvr_tokens[j]
            len_i = len(seq_i)
            len_j = len(seq_j)

            min_len = min(len_i, len_j)

            if min_len == 0:
                dist_norm = 1.0
            else:
                if config.motif in ["C{1,3}A", "TG{1,3}"]:
                    compare_len = min(min_len, 67)
                    if compare_len == 0:
                        dist_norm = 1.0
                    else:
                        trunc_seq_i = seq_i[:compare_len]
                        trunc_seq_j = seq_j[:compare_len]

                        dist = levenshtein(trunc_seq_i, trunc_seq_j)
                        dist_norm = dist / compare_len
                else:
                    trunc_seq_i = seq_i[:min_len]
                    trunc_seq_j = seq_j[:min_len]
                    dist = levenshtein(trunc_seq_i, trunc_seq_j)
                    dist_norm = dist / min_len

            dist_matrix[i, j] = dist_norm
            dist_matrix[j, i] = dist_norm

    if n < config.min_cluster_size:
        return [reads_list], set()

    min_cluster_size = config.min_cluster_size

    dynamic_min_samples = max(2, int(min_cluster_size * 0.8))
    if n <= 20:
        dynamic_min_samples = max(2, int(n * 0.2))

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        metric='precomputed',
        cluster_selection_epsilon=config.cluster_epsilon,
        min_samples=dynamic_min_samples,
        allow_single_cluster=True
    )

    labels = clusterer.fit_predict(dist_matrix)

    merged_clusters = []
    graph_outliers_idx = set()

    unique_labels = set(labels)
    for label in unique_labels:
        cluster_indices = np.where(labels == label)[0]

        if label == -1:
            graph_outliers_idx.update(cluster_indices)
        else:
            core_reads = [reads_list[idx] for idx in cluster_indices]
            merged_clusters.append(core_reads)

    merged_clusters.sort(key=len, reverse=True)

    return merged_clusters, graph_outliers_idx

def _get_token_maps(reads, local_tvr_map, canonical_set, backbone_motif):

    kmer_counts = Counter()
    for r in reads:
        for item in local_tvr_map.get(r, []):
            kmer_counts[item[1]] += 1

    core_kmers = set()
    for ref in canonical_set:
        core_kmers.update(get_cyclic_shifts(ref))

    max_core_capacity = 92

    for kmer, _ in kmer_counts.most_common():
        if len(core_kmers) >= max_core_capacity:
            break
        core_kmers.add(kmer)

    valid_chars = [chr(i) for i in range(33, 126) if i != 45]
    noise_char = chr(126)  # '~'

    char_map = {}
    for i, kmer in enumerate(sorted(list(core_kmers))):
        char_map[kmer] = valid_chars[i]

    for kmer in kmer_counts.keys():
        if kmer not in char_map:
            char_map[kmer] = noise_char

    inv_char_map = {v: k for k, v in char_map.items() if v != noise_char}
    inv_char_map[noise_char] = backbone_motif

    return char_map, inv_char_map

def _get_token_strings(reads, local_tvr_map, char_map):
    token_strings_dict = {}
    for r in reads:
        sorted_tvrs = sorted(local_tvr_map.get(r, []), key=lambda x: x[0])
        token_strings_dict[r] = "".join([char_map[t[1]] for t in sorted_tvrs])
    return token_strings_dict

def _build_consensus(c_reads, local_all_map, char_map, ref_char, config):
    c_full_token_strings = []
    for r_id in c_reads:
        read_tokens = [char_map.get(kmer, ref_char) for kmer in local_all_map[r_id]]
        c_full_token_strings.append("".join(read_tokens))

    if len(c_full_token_strings) == 1:
        consensus_token_string = c_full_token_strings[0]
        return consensus_token_string, consensus_token_string

    read_info = []
    for i, r_id in enumerate(c_reads):
        read_info.append({
            'id': r_id, 'seq': c_full_token_strings[i], 'len': len(c_full_token_strings[i])
        })

    if len(read_info) > config.max_depth:
        read_info.sort(key=lambda x: x['len'], reverse=True)
        sampled_reads = read_info[:config.max_depth]
    else:
        sampled_reads = read_info

    hq_token_strings = []
    for x in sampled_reads:
        seq = x['seq']
        if len(seq) > 2:
            hq_token_strings.append(seq[:-2])
        else:
            hq_token_strings.append(seq)

    aligner = pyabpoa.msa_aligner(
        aln_mode='e',cons_algrm='HB',is_ascii=True,
        match=2,mismatch=3,gap_open1=4,gap_ext1=2,
        gap_open2=20,gap_ext2=1,extra_b=-1)

    res = aligner.msa(hq_token_strings, out_cons=True, out_msa=False)
    raw_consensus = res.cons_seq[0]

    valid_chars = list(char_map.values())

    polished_consensus = telohmm.build_hmm_consensus(
        backbone=raw_consensus,
        reads=hq_token_strings,
        valid_chars=valid_chars,
        ref_char=ref_char,
        iterations=3,
        min_depth=3
    )

    if not polished_consensus:
        polished_consensus = raw_consensus

    return polished_consensus, raw_consensus

def _merge_pure_canonical_clusters(pre_merge_records, ref_char):

    pure_canonical_records = []
    other_records = []

    for record in pre_merge_records:
        if record['token_string'] and all(c == ref_char for c in record['token_string']):
            pure_canonical_records.append(record)
        else:
            other_records.append(record)

    if len(pure_canonical_records) > 1:
        merged_reads = [r for rec in pure_canonical_records for r in rec['reads']]
        rep_record = max(pure_canonical_records, key=lambda x: len(x['reads']))

        merged_record = {
            'reads': merged_reads,
            'token_string': rep_record['token_string'],
            'raw_consensus': rep_record['raw_consensus']
        }

        merged_records = other_records + [merged_record]
        merged_records.sort(key=lambda x: len(x['reads']), reverse=True)
        return merged_records

    return pre_merge_records

def _generate_rle_blocks(consensus_tvrs):
    blocks = []
    if consensus_tvrs:
        current_motif = consensus_tvrs[0]
        current_count = 1
        for kmer in consensus_tvrs[1:]:
            if kmer == current_motif:
                current_count += 1
            else:
                blocks.append((current_motif, current_count))
                current_motif = kmer
                current_count = 1
        blocks.append((current_motif, current_count))

    rle_parts = [f"({m}){c}" if c > 1 else f"({m})" for m, c in blocks]
    block_parts = [f"{m}:{c}" for m, c in blocks]

    rle_string = "".join(rle_parts) if rle_parts else "."
    block_string = ",".join(block_parts) if block_parts else "."
    return rle_string, block_string

def _format_plot_lines(reads, chrom, arm, local_raw_plot_data, hap_name):
    lines = []
    for r_id in reads:
        t_len, tvr_str, read_chrom, chrom_phase = local_raw_plot_data.get(r_id, (0, ".", chrom, "unphased"))
        lines.append(f"{r_id}\t{read_chrom}\t{chrom_phase}\t{arm}\t{hap_name}\t{t_len}\t{tvr_str}\n")
    return lines

def process_arm_haplotypes(chrom, arm, reads, local_tvr_map, local_raw_plot_data, local_all_map, canonical_set, backbone_motif, config):
    haplotype_results = []
    plot_lines = []

    if not reads:
        return haplotype_results, plot_lines

    char_map, inv_char_map = _get_token_maps(reads, local_tvr_map, canonical_set, backbone_motif)
    ref_char = char_map[backbone_motif]
    token_strings_dict = _get_token_strings(reads, local_tvr_map, char_map)
    reads_list = list(reads)

    merged_clusters, graph_outliers_idx = _cluster_reads(reads_list, token_strings_dict, config)
    pre_merge_records = []
    for c_reads in merged_clusters:
        if not c_reads: continue
        consensus_token_string, raw_consensus = _build_consensus(c_reads, local_all_map, char_map, ref_char, config)
        pre_merge_records.append({
            'reads': c_reads,
            'token_string': consensus_token_string,
            'raw_consensus': raw_consensus
        })

    pre_merge_records = _merge_pure_canonical_clusters(pre_merge_records, ref_char)

    valid_hap_idx = 1
    all_final_outliers = [reads_list[idx] for idx in graph_outliers_idx]

    for record in pre_merge_records:
        c_reads = record['reads']
        consensus_token_string = record['token_string']

        is_size_valid = (len(c_reads) >= config.min_cluster_size) or config.is_asm

        if is_size_valid:
            hap_name = f"C{valid_hap_idx}"
            valid_hap_idx += 1

            consensus_tvrs = [inv_char_map.get(c, backbone_motif) for c in consensus_token_string]
            stitched_sequence = "".join(consensus_tvrs)
            seq_length = len(stitched_sequence)
            rle_string, block_string = _generate_rle_blocks(consensus_tvrs)

            read_support = len(c_reads)
            hap_freq = read_support / len(reads)

            if stitched_sequence and stitched_sequence != ".":
                _length, _tvr, read_chrom, chrom_phase = local_raw_plot_data.get(c_reads[0], (0, ".", chrom, "unphased"))
                line = f"{read_chrom}\t{chrom_phase}\t{arm}\t{hap_name}\t{read_support}\t{hap_freq:.2f}\t{seq_length}\t{rle_string}\t{block_string}\t{stitched_sequence}\n"
                haplotype_results.append(line)

            plot_lines.extend(_format_plot_lines(c_reads, chrom, arm, local_raw_plot_data, hap_name))

        else:
            all_final_outliers.extend(c_reads)

    if all_final_outliers:
        plot_lines.extend(_format_plot_lines(all_final_outliers, chrom, arm, local_raw_plot_data, "Outlier"))

    return haplotype_results, plot_lines

def chunked_generator(iterable, n):
    it = iter(iterable)
    while True:
        chunk = list(itertools.islice(it, n))
        if not chunk:
            break
        yield chunk

def merge_summaries(global_summary, partial_summary):
    for chrom, arms in partial_summary.items():
        if chrom not in global_summary:
            global_summary[chrom] = defaultdict(lambda: defaultdict(int))
        for arm, repeats in arms.items():
            for repeat, count in repeats.items():
                global_summary[chrom][arm][repeat] += count

@lru_cache(maxsize=None)
def classify_repeat(unit, canonical_set_tuple):
    min_dist = float('inf')

    for ref in canonical_set_tuple:
        ref_shifts = get_cyclic_shifts(ref)
        dist = min(levenshtein(unit, s) for s in ref_shifts)
        if dist < min_dist:
            min_dist = dist

    if min_dist == 0:
        return "Canonical", "0"
    else:
        return "TVR", str(min_dist)

def filter_singleton_tvrs(
    tvr_summary,
    global_read_meta,
    global_tvr_map,
    global_all_map,
    canonical_set,
    config: TVRConfig
):
    MIN_ARM_READS = 5

    chrom_phase_arm_reads_filter = defaultdict(lambda: defaultdict(list))
    for read_id, (chrom, chrom_phase, arm) in list(global_read_meta.items()):
        chrom_phase_arm_reads_filter[(chrom, chrom_phase)][arm].append(read_id)

    singleton_tvr_dropped_count = 0

    for chrom_key in list(chrom_phase_arm_reads_filter.keys()):
        for arm in list(chrom_phase_arm_reads_filter[chrom_key].keys()):
            reads = chrom_phase_arm_reads_filter[chrom_key][arm]
            if len(reads) < MIN_ARM_READS:
                continue

            arm_summary = tvr_summary[chrom_key][arm]

            singleton_tvrs = set()
            for unit, count in list(arm_summary.items()):
                if count == 1:
                    rpt_group, _ = classify_repeat(unit, canonical_set)
                    if rpt_group != "Canonical":
                        singleton_tvrs.add(unit)

            if not singleton_tvrs:
                continue

            for r in reads:
                if r in global_tvr_map:
                    global_tvr_map[r] = [item for item in global_tvr_map[r] if item[1] not in singleton_tvrs]

                if r in global_all_map:
                    global_all_map[r] = [kmer for kmer in global_all_map[r] if kmer not in singleton_tvrs]

            for unit in singleton_tvrs:
                if unit in arm_summary:
                    del arm_summary[unit]
                    singleton_tvr_dropped_count += 1

    return 0, singleton_tvr_dropped_count

def resolve_motif_semantics(std_motif: str):
    if std_motif == "TG{1,3}":
        return "TG{1,3}", ("TG", "TGG", "TGGG"), "TG"

    return std_motif, (std_motif,), std_motif

def find_tvr(
        telseq: Union[str, Path],
        outdir: Union[str, Path],
        prefix: str,
        config: TVRConfig,
        threads: int = 4,
        logger = None
    ):

    logger = logger or log_utils.get_logger()
    outdir = Path(outdir)
    k_values = [int(x) for x in config.kmers.split(',')]

    primary_motif = config.motif.split('|')[0] # for ont_r9 motif, e.g. CCCTAA|TTTTAA|CCCTGG|CTTCTT
    motif_dict = telox_utils.parse_motifs(primary_motif)

    std_motif = motif_dict.get('R', motif_dict.get('q', primary_motif))
    display_motif, canonical_set, backbone_motif = resolve_motif_semantics(std_motif)

    output_count_file = outdir / f"{prefix}.TVR.count.tsv"
    output_plot_data = outdir / f"{prefix}.TVR.plot_data.tsv"

    tvr_summary = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))

    global_tvr_map = {}
    global_read_meta = {}
    global_raw_plot_data = {}
    global_all_map = {}

    logger.info(f"Identifying TVR motifs using k-mers: {config.kmers}")

    fasta_gen = read_fasta_generator(str(telseq))

    with ProcessPoolExecutor(max_workers=threads) as executor:
        futures = []
        for _, chunk in enumerate(chunked_generator(fasta_gen, config.chunk_size)):
            future = executor.submit(
                process_chunk_data,
                chunk,
                k_values,
                canonical_set,
                backbone_motif,
                config.min_tvr_copy,
                config.include_canonical
            )
            futures.append(future)

        for future in futures:
            try:
                partial_summary, partial_plot_data, partial_tvr,partial_all_map, partial_meta = future.result()

                global_raw_plot_data.update(partial_plot_data)
                merge_summaries(tvr_summary, partial_summary)

                global_tvr_map.update(partial_tvr)
                global_read_meta.update(partial_meta)
                global_all_map.update(partial_all_map)

            except Exception as e:
                logger.error(f"Worker failed: {e}")

    _, dropped_tvr_cnt = filter_singleton_tvrs(
        tvr_summary,
        global_read_meta,
        global_tvr_map,
        global_all_map,
        canonical_set,
        config
    )
    if dropped_tvr_cnt > 0:
        pass
        #logger.info(f"Filtered {dropped_tvr_cnt} singleton TVRs.")

    logger.info(f"Writing arm-level TVR counts to: {output_count_file.name}")
    with open(output_count_file, 'w') as f_count:
        f_count.write(f"chrom\tchrom_phase\tarm\tgroup\tedit_distance\tmotif\tcount\tfrequency\n")

        sorted_chroms = sorted(tvr_summary.keys(), key=lambda key: (natsort_key(key[0]), natsort_key(key[1])))

        for chrom, chrom_phase in sorted_chroms:
            arms_data = tvr_summary[(chrom, chrom_phase)]
            for arm in sorted(arms_data.keys()):
                current_repeats = arms_data[arm]
                total_units_count = sum(current_repeats.values())

                if total_units_count == 0:
                    continue

                rows_to_write_count = []
                for unit, count in current_repeats.items():
                    rpt_group, rpt_type = classify_repeat(unit, canonical_set)
                    freq = count / total_units_count

                    rows_to_write_count.append((rpt_group, rpt_type, unit, count, freq))

                rows_to_write_count.sort(key=lambda x: (1 if x[0] == "Canonical" else 0, x[4]), reverse=True)
                for r_group, r_type, unit, count, freq in rows_to_write_count:
                    f_count.write(f"{chrom}\t{chrom_phase}\t{arm}\t{r_group}\t{r_type}\t{unit}\t{count}\t{freq:.5f}\n")

    output_haplotype_file = outdir / f"{prefix}.TVR.haplotype.tsv"

    chrom_phase_arm_reads = defaultdict(lambda: defaultdict(list))
    for read_id, (chrom, chrom_phase, arm) in global_read_meta.items():
        chrom_phase_arm_reads[(chrom, chrom_phase)][arm].append(read_id)

    with open(output_haplotype_file, 'w') as f_hap, \
         open(output_plot_data, 'w') as f_raw_plot:
        f_hap.write("chrom\tchrom_phase\tarm\ttvr_hap\tread_support\thap_frequency\thap_length\tmotif_rle\tmotif_blocks\tconsensus_sequence\n")
        f_raw_plot.write("read_id\tchrom\tchrom_phase\tarm\ttvr_hap\ttel_length\ttvrs\n")

        logger.info(f"Clustering reads to generate TVR haplotype consensus...")
        with ProcessPoolExecutor(max_workers=threads) as executor:
            future_to_arm = {}
            for chrom, chrom_phase in sorted(chrom_phase_arm_reads.keys(), key=lambda key: (natsort_key(key[0]), natsort_key(key[1]))):
                for arm in sorted(chrom_phase_arm_reads[(chrom, chrom_phase)].keys()):
                    reads = chrom_phase_arm_reads[(chrom, chrom_phase)][arm]
                    if len(reads) == 0: continue

                    local_tvr_map = {r: global_tvr_map[r] for r in reads if r in global_tvr_map}
                    local_raw_plot_data = {r: global_raw_plot_data[r] for r in reads if r in global_raw_plot_data}
                    local_all_map = {r: global_all_map[r] for r in reads if r in global_all_map}

                    future = executor.submit(
                        process_arm_haplotypes, chrom, arm, reads, local_tvr_map,
                        local_raw_plot_data, local_all_map, canonical_set, backbone_motif, config
                    )
                    future_to_arm[future] = (chrom, chrom_phase, arm)

            for future in future_to_arm:
                chrom, chrom_phase, arm = future_to_arm[future]
                try:
                    result_lines, raw_plot_lines = future.result()

                    for line in result_lines:
                        f_hap.write(line)
                    for line in raw_plot_lines:
                        f_raw_plot.write(line)

                except Exception as e:
                    logger.error(f"Haplotype generation failed for {chrom} {arm}: {e}")
